/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Profs;


import java.util.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Collections;


/**
 *
 * @author student
 */
public class Prof extends javax.swing.JFrame {
    
        
        public String x;
        int a=0;
        int b=0;
        int c=0;
        int d=0;
        int e=0;
        int f=0;
        
        HashMap<String, Integer> hash_map = new HashMap<>();
        
        //double smallestVal = Collections.min(hash_map.values());
        
        public void FillComboBox()
        {
            hash_map.put("Prof Pušnar", a);
            hash_map.put("Prof Blažič", b);
            hash_map.put("Prof Ferjančič", c);
            hash_map.put("Prof Vogrinc", d);
            hash_map.put("Prof Janežič", e);
            hash_map.put("Prof Pirc", f);
            
            for(Map.Entry entry: hash_map.entrySet())
            {
                Object Items=entry.getKey();
                ComboBoxProf.addItem((String)Items);
                
            }
        }
        
        
        
        
        
        

    /**
     * Creates new form Prof
     */
    public Prof() {
        initComponents();
        FillComboBox();
        ComboBoxProf.setSelectedItem(null);
        izpis.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GumbOcena6 = new javax.swing.JButton();
        GumbOcena5 = new javax.swing.JButton();
        GumbOcena4 = new javax.swing.JButton();
        ComboBoxProf = new javax.swing.JComboBox<>();
        GumbOcena3 = new javax.swing.JButton();
        GumbOcena2 = new javax.swing.JButton();
        GumbOcena1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        izpis = new javax.swing.JTextArea();
        GumbSestevek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GumbOcena6.setText("1.Najboljsi +3");
        GumbOcena6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena6ActionPerformed(evt);
            }
        });

        GumbOcena5.setText("2.Najboljsi +2");
        GumbOcena5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena5ActionPerformed(evt);
            }
        });

        GumbOcena4.setText("3.Najboljsi +1");
        GumbOcena4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena4ActionPerformed(evt);
            }
        });

        ComboBoxProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxProfActionPerformed(evt);
            }
        });

        GumbOcena3.setText("1.Najslabsi -3");
        GumbOcena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena3ActionPerformed(evt);
            }
        });

        GumbOcena2.setText("2.Najslabsi -2");
        GumbOcena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena2ActionPerformed(evt);
            }
        });

        GumbOcena1.setText("3.Najslabsi -1");
        GumbOcena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbOcena1ActionPerformed(evt);
            }
        });

        izpis.setColumns(20);
        izpis.setRows(5);
        jScrollPane1.setViewportView(izpis);

        GumbSestevek.setText("Zaključi");
        GumbSestevek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GumbSestevekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxProf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GumbOcena3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GumbOcena6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GumbOcena2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GumbOcena5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GumbOcena4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GumbOcena1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GumbSestevek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GumbOcena6)
                            .addComponent(GumbOcena5)
                            .addComponent(GumbOcena4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GumbOcena3)
                            .addComponent(GumbOcena2)
                            .addComponent(GumbOcena1)))
                    .addComponent(ComboBoxProf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GumbSestevek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxProfActionPerformed
        // TODO add your handling code here:
        
        //x=ComboBoxProf.getSelectedItem().toString();
        
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        //izpis.setText(String.valueOf(hash_map.get(ItemName)));
        
    }//GEN-LAST:event_ComboBoxProfActionPerformed

    private void GumbOcena6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena6ActionPerformed
        // TODO add your handling code here:
       // int s=Integer.parseInt(x);
       
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score + 3);
        izpis.setText(ItemName+" ima oceno "+(score+3)+"\n");
        
    }//GEN-LAST:event_GumbOcena6ActionPerformed

    private void GumbOcena5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena5ActionPerformed
        // TODO add your handling code here:
        //int s=Integer.parseInt(x);
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score + 2);
        izpis.setText(ItemName+" ima oceno "+(score+2)+"\n");
    }//GEN-LAST:event_GumbOcena5ActionPerformed

    private void GumbOcena4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena4ActionPerformed
        // TODO add your handling code here:
        //int s=Integer.parseInt(x);
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score + 1);
        izpis.setText(ItemName+" ima oceno "+(score+1)+"\n");
    }//GEN-LAST:event_GumbOcena4ActionPerformed

    private void GumbOcena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena3ActionPerformed
        // TODO add your handling code here:
        //int s=Integer.parseInt(x);
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score -3);
        izpis.setText(ItemName+" ima oceno "+(score-3)+"\n");
    }//GEN-LAST:event_GumbOcena3ActionPerformed

    private void GumbOcena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena2ActionPerformed
        // TODO add your handling code here:
        //int s=Integer.parseInt(x);
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score -2);
        izpis.setText(ItemName+" ima oceno "+(score-2)+"\n");
    }//GEN-LAST:event_GumbOcena2ActionPerformed

    private void GumbOcena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbOcena1ActionPerformed
        // TODO add your handling code here:
        //int s=Integer.parseInt(x);
        String ItemName= (String) ComboBoxProf.getSelectedItem();
        
        int score=hash_map.get(ItemName);
        
        hash_map.put(ItemName, score - 1);
        izpis.setText(ItemName+" ima oceno "+(score-1)+"\n");
    }//GEN-LAST:event_GumbOcena1ActionPerformed

    private void GumbSestevekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GumbSestevekActionPerformed
        // TODO add your handling code here:ž
        izpis.setText("");
        for (Map.Entry<String,Integer> entry : hash_map.entrySet()) 
            izpis.append( entry.getKey()+" ima oceno: "+ entry.getValue()+"\n");
        //izpis.append("Prof 1 ima oceno "+a+"\n"+("Prof 2 ima oceno "+b+"\n")+("Prof 3 ima oceno "+c+"\n")+("Prof 4 ima oceno "+d+"\n")+("Prof 5 ima oceno "+e+"\n")+("Prof 6 ima oceno "+f));
        
    }//GEN-LAST:event_GumbSestevekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        int s=0;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxProf;
    private javax.swing.JButton GumbOcena1;
    private javax.swing.JButton GumbOcena2;
    private javax.swing.JButton GumbOcena3;
    private javax.swing.JButton GumbOcena4;
    private javax.swing.JButton GumbOcena5;
    private javax.swing.JButton GumbOcena6;
    private javax.swing.JButton GumbSestevek;
    private javax.swing.JTextArea izpis;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
